### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by lubeda** [trip5/Matrix-Fonts#1]
Hi, trhe link to the MatrixClock-Light8 font is wrong
https://github.com/darkpoet78/MatrixClockFonts/blob/main/8-series/MatrixClock-Light8.bsd should be https://github.com/darkpoet78/MatrixClockFonts/raw/main/8-series/MatrixClock-Light8.bdf

**Comment by trip5** [comment]
Oh lol.  I was so busy trying to fix what's going on with the encoding that I didn't even check.

Thanks.
