### ISSUE TITLE
[Language Request] <title>support vietnamese

### ISSUE THREAD

**Issue by lesongbang** [trip5/Matrix-Fonts#11]
### Information

Một số kí tự việt nam chưa hiển thị được.xin hổ trợ giúp ạ

**Comment by trip5** [comment]
Alright.  Does that mean most characters do work?  I'm guessing Vietnamese shares a lot of characters from the European sets.

Can you take a look here?  https://usefulwebtool.com/characters-vietnamese  And answer this... is it the characters in the 7000-range that do not display correctly?

I took a look at https://stackoverflow.com/questions/37579692/unicode-range-for-vietnamese and there's some good information for me here too but it makes me wonder about 8 pixels... I'm counting a minimum of 11 different accent marks above letters - ĂẰẲẴẮẶÂẦẨẪẤ - maybe more?  Even for the European & Cyrillic letters, many of accents ended up looking very similar.

**Comment by trip5** [comment]
I'd still like your input but it's been added anyway!

**Comment by lesongbang** [comment]
bước đầu tôi thấy hiển thị tiếng việt tốt trong điều kiện 8*32 điểm ảnh. cảm ơn bạn nhiều.

**Comment by trip5** [comment]
Let me know if there are any problems!
