### ISSUE TITLE
[Character Problem] Inconsistent spacing between characters

### ISSUE THREAD

**Issue by ruliane** [trip5/Matrix-Fonts#12]
### Information

I try to use **MatrixLight6**, **MatrixChunky6** and **MatrixChunky8** on a 32*8 matrix LED. However, spacing between characters is not consistent.

- a, b, s, H, R and 1 are followed by a small spacing (which is the good behavior, I guess)

- others characters are followed by 5 pixels. I tested only characters [a-zA-Z0-9].
It looks like a blank character is included between each.

Am I missing something?

Below is a picture:
![DSC_0462](https://github.com/user-attachments/assets/36cc49ae-4991-432f-8a02-f6e07d1add43)

**Comment by ruliane** [comment]
May it be related to #2 ?

**Comment by trip5** [comment]
I don't think this related to #2 - which was just my eyes missing correct spacing in few characters. Sounds like you're experiencing something much weirder, especially since in your above example, you're getting EXACTLY the distance of a full character as a space... are they all like that?

Also, what platform are you on?  I (and a few others I can verify) have used ESPHome and there are no such errors.  I expect it's useable in ArduinoIDE or PlatformIO... but...?

Also, are you only using the regular ASCII Latin or are you mixing it up with any other characters?  Anywhere in your code?  This feels like a Unicode-related issue... but more information would be helpful.

**Comment by trip5** [comment]
Oh also which fonts are you using?  BDF or TTF?

**Comment by ruliane** [comment]
I missed an important piece of information! I'm actually working Raspberry Pi.
I use the Python library [PIL.ImageFont](https://pillow.readthedocs.io/en/latest/reference/ImageFont.html) to load font and display text on the matrix. I use TTF font (and I'm not sure it supports BDF fonts).

It seems to me like a encoding issue, but my Python script contains only ASCII Latin characters. I even tried with a simplified version, directly in Python shell. Same result. :(

> are they all like that?

Almost. Characters `a`, `b`, `s`, `H`, `R` and `1` appear correctly.

**Comment by trip5** [comment]
If you're only using Latin characters... Maybe try the BDF version?  I know certainly that Pillow supports BDF files (except when using Unicode characters - argh - seriously, I spent too many hours just to find that out).

But it may also be a Pillow-version issue too.  You can try upgrading or rolling back... a few years even.  I just checked and it looks like ESPHome is using 10.2.0 which has no issues with the TTF files - unsure about BDF.  When I made the switch to recommending TTF, ESPHome was stuck on Pillow 6-something (seriously) which worked very well with BDF files but had Unicode issues.  It's possible your OS is also stuck on a weird version...?

Possibly check if you can re-encode the python script file using Notepad++?  I'm not sure if using ANSI or some other encoding would cause errors like you're seeing.  All I can think it's that it's a Unicode and/or Pillow issue as I'd be getting a lot more bug reports if only 6 characters were correct!

Probably I can't help you much more.  I'm a script monkey when it comes to Python...

**Comment by andrewjswan** [comment]
I encountered a similar problem in ESPHome in Venv, as it turned out the problem was in PIL and dependencies. I switched to ESPHome container, the problem disappeared.

**Comment by ruliane** [comment]
I'm using the PIL module available in Raspbian Bookworm's APT repository:
```
Package: python3-pil
Version: 9.4.0-1.1+deb12u1
```

**I just tried the BDF version: it works!** All characters are corrects, most of them being 3-px wide plus an extra 1px column.

TBH I don't understand how/why Pillow support BDF files through the `truetype()` function. Are BDF files actually TrueType fonts?

Anyway, the BDF versions is not affected by this issue. For now, the problem appears only in specific conditions: TTF used with PIL. I will try some other versions of PIL and update this thread.

**Comment by trip5** [comment]
Huh.  I can't even answer that.  I know Opentype fonts are also supported under the same function.  I imagine that Pillow just looks at the first few bytes of the file to determine what kind of file it's working with.  BDF files are just bitmaps.  They can't be anything more. TrueType fonts can be a mix of rasters, vectors, shading, hinting... but can also include bitmaps (which is how mine are made)... but many TTF files do not include bitmaps at all (although if I recall, Courier and some other common Windows fonts have bitmaps for the a certain pixel height (10? 12?) - so as to be usable in command prompt windows.

Pillow converts the font into bitmaps usable by Arduino/C++ code (binary definitions of fonts arranged as an array).  So, there's a bug in Pillow 9.4 that screws up the rendering process.  You could try upgrading (or downgrading) your Pillow version... I'd be willing to bet that Pillow 10 works fine for TTF... BUT... if you've already got a working solution, just do that, right?

If you need to use Unicode at all, go for Pillow 10.  As I said, that's the one included in ESPHome Docker container and it functions on the TTF perfectly.  Now, I'm just curious why Raspbian is stuck on an old version of Pillow... https://pillow.readthedocs.io/en/stable/releasenotes/9.4.0.html  Although I will say it took quite a bit of bug-reporting on ESPHome Docker to even switch from the original PIL (version 6?) to Pillow and keep the container updated properly.  I'm guessing it has something to do with Python and other dependencies that I can't begin to understand.
