### ISSUE TITLE
[Character Problem] Wishes after use, space, Cyrillic M

### ISSUE THREAD

**Issue by andrewjswan** [trip5/Matrix-Fonts#7]
### Information

- To widen the space (#32) in the MatrixChunky6/8 font a bit (2 dots):
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/278bba06-6f09-4f14-b7d4-8903bb6998ab)

- Make M Cyrillic more classical:
MatrixChunky8:
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/abd4cc9f-2e7c-4e2e-8566-7743d9460666)
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/ee06853d-2ff6-4120-8d22-addd52f7d864)

PS: For some reason MatrixChunky6 TTF font displays space on Matrix in 3 dots. :(

**Comment by trip5** [comment]
Yeah I did a little search of Cyrillic Em.  It's similar as English M but, you're right... of course you are.  Lol.  I'll get on it.

This image helped and gives decent idea how a 6-pixel Cyrillic font would look:
![image](https://github.com/trip5/Matrix-Fonts/assets/19512466/36dd8721-5172-473b-900d-75392039b150)
Personally, I think it's hideous but... I don't know.  What do you think?

As for the spaces... I think now that Unicode is working I can actually add other options for spaces, too!  I'll put some note on the Readme to make it easy to copy and paste.

Hair/Thin space: 1 pixel
Regular space: 2 pixels
En space: 3 pixels
Em space: 4 pixels

**Comment by trip5** [comment]
Also, updating the Light Cyrillic Ems to a similar style...

![image](https://github.com/trip5/Matrix-Fonts/assets/19512466/79cb98c3-0606-4488-8c96-09eb4fbf8912)

![image](https://github.com/trip5/Matrix-Fonts/assets/19512466/2ed01e45-d68b-46db-b346-71e93f639728)

**Comment by trip5** [comment]
Github updated.  Check it out...

**Comment by andrewjswan** [comment]
> Also, updating the Light Cyrillic Ems to a similar style...

Super for Light

**Comment by andrewjswan** [comment]
> This image helped and gives decent idea how a 6-pixel Cyrillic font would look:

5 dots in height?

**A** - Ok
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/53e28bbb-4050-4997-976c-7b2071cd19c6)
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/cf76be58-dbbd-4655-b0da-aa0afd0391de)
**О П Р С** - Ok!
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/e70ba6be-716f-4f84-b1ce-e8fcadf1dace)
**Ф** - Ok!
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/8d4b8e08-1545-4970-b544-2f5167dc67d5)
**Ш Щ** - Ok!
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/090d0067-53f0-4017-a5aa-2970d9866e05)
**Ы Ь Э Ю** - Ок!
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/651f5527-6171-4262-bd85-42ae9ce9c2bb)

Don't forget these :)
![image](https://github.com/trip5/Matrix-Fonts/assets/3609660/895e134d-7f26-4095-9322-2ac04ee1600e)

In my opinion this is more correct...

**Comment by andrewjswan** [comment]
Super! Thanks :)
![IMG_20231013_182214](https://github.com/trip5/Matrix-Fonts/assets/3609660/1392e69c-0113-4762-ac33-4f80ef3f8fd9)

**Comment by trip5** [comment]
Yeah it looks pretty good.  월 (Monday) is pretty messed-up but... kind of recognizable.  Slowly inching my way through adding Cyrillic to the 6-series BTW.  Korean just won't be there I think... mostly thanks to that character.  Lol.

**Comment by trip5** [comment]
Added Cyrillic to the 6-series.  Had to mash some of the lower-case characters down a bit (esp. on the non-X fonts).  I think they look just OK.  Not much to do when working with 5 pixels.  Test it out if you like... I'll close this thread for now but you can come back if there's problems.
