### ISSUE TITLE
[Issue] Adding a symbol that would appear as one empty line

### ISSUE THREAD

**Issue by andrewjswan** [trip5/Matrix-Fonts#8]
### Information

Adding a symbol that would appear as one empty line will be convenient where you need to add a small empty separator.

**Comment by trip5** [comment]
There are already 2 symbols available with empty single row of pixels... Is that what you mean?

**Comment by andrewjswan** [comment]
I didn't find different from space (32), what's the second one?

**Comment by trip5** [comment]
Check here:
https://github.com/trip5/Matrix-Fonts?tab=readme-ov-file#spaces

I'm not entirely certain these types of spaces work as intended so that's why I added:

https://github.com/trip5/Matrix-Fonts?tab=readme-ov-file#pixel-spaces-that-can-be-used-as-characters

**Comment by andrewjswan** [comment]
Sorry! I was blind! As usual, the documentation has everything I need.
Thanks a lot :)
